### ISSUE TITLE
Support for AEG ovens

### ISSUE THREAD

**Issue by cscheiene** [gslender/com.electrolux-aeg.ocp#1]
The device is found when adding a it as an unknown device. Support for AEG ovens would be nice.

**Comment by gslender** [comment]
As per the readme, include the logs as I can't add a device I know nothing about

**Comment by cscheiene** [comment]
Link in the Readme file does not work

**Comment by cscheiene** [comment]
Report from Homey ec1c8ca0-2f5d-403a-854f-6b479ce0c647

**Comment by gslender** [comment]
Link fixed. Pls follow it

**Comment by gslender** [comment]
Sorry about the confusion... the New Device Request page has been fixed and is now working.

**Comment by gslender** [comment]
Thanks for submitting the diag report that contained enough details for me to add Oven support. 

Please check the TEST release to see if this works??

https://homey.app/en-au/app/com.electrolux-aeg.ocp/Electrolux-AEG/test/

**Comment by cscheiene** [comment]
Thanks, not home at the moment but tested briefly and data seems correct. 
![Screenshot_20240722_090056](https://github.com/user-attachments/assets/8d7f26cf-9f5e-49c3-a7a3-30ae7a4ca851)

**Comment by gslender** [comment]
Have updated the test version to include cavity light control and also sending start/stop command, which if works, will be looking to add cooking programs and modes - the same is being added to the similar laundry appliances

**Comment by cscheiene** [comment]
Works well. Not tested flows yet. FYI, I see that new device classes are available from firmware 12. https://apps-sdk-v3.developer.homey.app/tutorial-device-classes.html
