### ISSUE TITLE
New Device: vacuumrobot Pure i9.2

### ISSUE THREAD

**Issue by viwi1** [gslender/com.electrolux-aeg.ocp#10]
{"applianceId":"900277470124007901100106","applianceData":{"applianceName":"Johnny","created":"2024-09-12T19:55:45.2567888Z","modelName":"PUREi9"},"properties":{"desired":{},"reported":{"availableLanguages":["deu","eng","fra","pol","spa","kor","zht","zhs","jpn","ces","ita","rus"],"capabilities":{"CustomPlay":{},"FreezeMapOnDemand":{},"InteractiveMap":{},"MultipleScheduledCleaningsPerDay":{},"PowerLevels":{},"PowerZones":{}},"batteryStatus":5,"robotStatus":10,"messageList":{"messages":[]},"dustbinStatus":"connected","platform":"1.01","applianceName":"Johnny","firmwareVersion":"43.23","language":"eng","mute":true,"powerMode":1},"metadata":null},"status":"enabled","connectionState":"Connected"}

Capacity: {}

Old library: https://github.com/Phype/purei9_unofficial

product webpage: https://www.electroluxhome.se/dammsugare/robotdammsugare/pi92-6dgm/

To request a new device, install the Electrolux/AEG OCP Homey App

Add your email and password to the app Configure settings.

Then add a New Device, choose the Electrolux/AEG OCP app Brand, and choose the Unknown device and if you have any appliance, it should be found and added. 

I will need the Appliance State {json} and Appliance Capabilities {json} files that are published in the device Advanced Settings when you install the Unknown device. Include these two data files in your submission below.

Without this information, we cannot add support for your device, and the issue will be closed.

For example:

```
2024-06-28T03:07:51.553Z [log] [ElectroluxAEGApp] [{"applianceId":"XXXXXXXX_01:xxxxxxx-xxxxxx","applianceData":{"applianceName":"Dryer","created":"2024-06-25T06:35:21.260Z","modelName":"TD"},"properties":{"desired":{},"reported":{"doorState":"OPEN","timeToEnd":-1,"networkInterfaceAlwaysOn":"ON","miscellaneous":{},"applianceUiSwVersion":"URDB0A3H","applianceTotalWorkingTime":7200,"remoteControl":"NOT_SAFETY_RELEVANT_ENABLED","dryingNominalLoadWeight":65535,

        <<SNIP WE'VE SHORTENED THIS FOR THE EXMAPLE, PLUS PLEASE KEEP THE ENTIRE JSON IN YOUR COPY/PASTE>>

"tDEconomy_Eco":false,"tDEconomy_Quick":false,"refresh":false,"dryingTime":65535,"memoryId":20,"programUID":"MACHINE_SETTINGS_HIDDEN_TEST","antiCreaseValue":255,"tDEconomy_Night":false},"cycleMemory1":{"reversePlus":false,"tDEconomy_Eco":false,"tDEconomy_Quick":false,"refresh":false,"dryingTime":65535,"memoryId":30,"programUID":"MACHINE_SETTINGS_HIDDEN_TEST","antiCreaseValue":255,"tDEconomy_Night":false}},"metadata":{}},"status":"enabled","connectionState":"connected"}]
```

Finally, please link to more information about the device, e.g. the manufacturer's website to assist with images and icons that will be needed to complete the app update and publish in the app store.

**Comment by gslender** [comment]
Interesting - this device seems to barely report any features or capabilities - what is available via the AEG iOS app? Can you share screenshots of what it supposedly possible? The JSON you've provided seems to offer very little.

**Comment by viwi1** [comment]
Iva added a screenshot, but it is in Swedish. Maybe the library i linked can help? Just to turn it on would be enough :)
![IMG_3674](https://github.com/user-attachments/assets/af423991-b332-418d-aef2-f7e6ed4c7eb6)

**Comment by gslender** [comment]
Just to turn it on might be all that we can do 😂

**Comment by viwi1** [comment]
Thank you!!

**Comment by gslender** [comment]
Are you 100% sure there is no Appliance Capabilities json in the Other Device in Homey?

I take it the above is from the Appliance State ??

Annoyingly, there is no mention of how to start/stop the device in terms of what command it would accept. Normally that's listed in the Appliance Capabilities json - which means this device isn't really working the same way as other appliances do in terms of the API etc.

**Comment by gslender** [comment]
What is the name of the iOS app you have installed to work the Robot Vacuum ??

**Comment by viwi1** [comment]
See attached :)
![IMG_3675](https://github.com/user-attachments/assets/7ae0ad4e-5649-4032-8950-0a8c6b135ca3)
![IMG_3676](https://github.com/user-attachments/assets/f58d8d46-cf55-4f08-81a0-72aa147ee3f4)
![IMG_3677](https://github.com/user-attachments/assets/fb951010-a455-4671-afef-61237afd2324)

**Comment by gslender** [comment]
Can you stop and restart the Homey AEG app, just to be 100% sure it doesn't spew up any json in the restart/reconnect of the device to the account etc

**Comment by gslender** [comment]
Also send me a diag so I can see what is happening under the hood

**Comment by viwi1** [comment]
cc07d8bb-9d90-4e79-8b90-4ab399eb9c87

Booted app, still no JSON
![IMG_3679](https://github.com/user-attachments/assets/217ffcd9-1b92-4fa4-8af0-0399d41d4dce)
![IMG_3678](https://github.com/user-attachments/assets/27adf5d8-fd61-4ff2-9288-f77902639aaf)

**Comment by gslender** [comment]
Okay.... I think I may have figured out enough to support the robot vac....

```
"execute_command",
    /*
        START => sendCommand({"CleaningCommand": "play"})
        PAUSE => sendCommand({"CleaningCommand": "pause"})
        RESUME => sendCommand({"CleaningCommand": "play"})
        STOPRESET => sendCommand({"CleaningCommand": "stop"})
        
     */
    "measure_battery", /* "batteryStatus", */
    "measure_applianceState", /* "robotStatus", */
    "measure_applianceMode",  /* "powerMode", */
    "measure_alerts" /* "messageList": { "messages": [] }, */
```

**Comment by gslender** [comment]
Try this test app

https://homey.app/a/com.electrolux-aeg.ocp/test/

**Comment by viwi1** [comment]
Everything works except ”Return home”

**Comment by viwi1** [comment]
Would be perfect if you could include flow to start the robot in the next version

**Comment by gslender** [comment]
Done. Next push and should be available as production (so eventually get off the test build)
