### ISSUE TITLE
Time to end oven isent working

### ISSUE THREAD

**Issue by Heha16** [gslender/com.electrolux-aeg.ocp#12]
Time to end isnt gattering any information from the app to Homey.

**Comment by gslender** [comment]
What appliance specifically is this for?

**Comment by Heha16** [comment]
Hi
Electrolux integrated steamovn OOS1080NZ


man. 16. sep. 2024 kl. 20:07 skrev GSlender ***@***.***>:

**Comment by gslender** [comment]
Follow the advice to get the json state and capabilities, post them here and I can take a look at what is going on.

**Comment by Heha16** [comment]
{"applianceId":"944184957_02:24652777-443E073996CD","applianceData":{"applianceName":"Olgaovn","created":"2024-09-03T13:27:54.951Z","modelName":"OV"},"properties":{"desired":{},"reported":{"doorState":"CLOSED","temperatureRepresentation":"CELSIUS","timeToEnd":-1,"remoteControl":"NOT_SAFETY_RELEVANT_ENABLED","targetTemperatureF":302,"targetTemperatureC":150,"program":"TRUE_FAN","displayFoodProbeTemperatureC":0,"startTime":-1,"waterTankEmpty":"STEAM_TANK_FULL","waterTrayInsertionState":"INSERTED","targetDuration":0,"applianceInfo":{"applianceType":"OV"},"displayFoodProbeTemperatureF":32,"targetFoodProbeTemperatureC":-17.833333333333332,"targetFoodProbeTemperatureF":-0.1,"runningTime":0,"applianceState":"READY_TO_START","alerts":[],"displayTemperatureC":30,"networkInterface":{"linkQualityIndicator":"GOOD","otaState":"IDLE"},"foodProbeInsertionState":"NOT_INSERTED","displayTemperatureF":86,"cavityLight":false,"processPhase":"NONE","connectivityState":"connected"},"metadata":{}},"status":"enabled","connectionState":"connected"}


{"alerts":{"access":"read","type":"alert","values":{"AD_CONVERTER_REFERENCE_ALARM":{},"BACKLIGHT_ALARM":{},"BOARD_TEMPERATURE_ALARM":{},"COMMUNICATION_ALARM_BETWEEN_TWO_CONTROLLERS":{},"COMMUNICATION_ALARM_OUI_OC":{},"CONFIGURATION_CHECKSUM_ALARM":{},"CONFIGURATION_COHERENT_ALARM":{},"CONFIGURATION_COMPATIBILITY_ALARM":{},"COOKING_FAN_CONFIG_ALARM":{},"DATA_FLASH_ALARM_UI":{},"DOOR_LOCK_ACTUATOR":{},"DOOR_LOCK_CONFIGURATION_ALARM":{},"DOOR_LOCK_SENSOR_ALARM":{},"ELECTRONIC_CLIXON_ALARM":{},"FIX_SENSOR_DETECTION_ALARM":{},"FOOD_PROBE_COMMUNICATION_ALARM":{},"FOOD_PROBE_CONFIGURATION_ALARM":{},"FUNCTION_SELECTOR_NOT_CONNECTED":{},"HMI-TOUCH_BOARD_FMEA_ALARM":{},"HMI-TOUCH_BOARD_SERIAL_COMMUNICATION_ALARM":{},"HOB_OVEN_COMMUNICATION_ALARM":{},"HOB_OVEN_POWER_MANAGEMENT_ALARM":{},"HUMIDITY_SENSOR_OUT_OF_RANGE_ALARM":{},"INTERNAL_ERROR":{},"LIB_FMEA_ALARM_ROTARY_GRAB":{},"MACS_COMMNUNICATION_ERROR":{},"MEAT_PROBE_OUT_OF_RANGE_ALARM":{},"NETVM_COMMUNICATION_ALARM":{},"NIUX_COMMUNICATION_ALARM":{},"NIUX_ONBOARDING_FAILED_ALARM":{},"NTC_OUT_OF_RANGE_ALARM":{},"OTA_FAILURE":{},"PERIPHERAL_INIT_ALARM_ROTARY_SERIAL_COMMUNICATION_ALARM":{},"PERIPHERAL_RUNTIME_ALARM_ROTARY_BIT_ENCODER_ALARM":{},"POWER_ALARM":{},"PT500_OUT_OF_RANGE_ALARM":{},"PT500_STEAM_OUT_OF_RANGE_ALARM":{},"PTO_COMMUNICATION_ALARM_OUI_PTO":{},"PTO_CONFIGURATION_CHECKSUM_ALARM":{},"PTO_KEY_ALARM":{},"PTO_LIB_FMEA_ALARM":{},"PYR_HOB_ALARM":{},"ROTARY_TOUCH_ALARM":{},"RTC_ALARM":{},"RTC_OUT_OF_RANGE_ALARM":{},"SMART_ADC_ERROR":{},"SMART_AD_CALIBRATION_RUNNING_ERROR":{},"SMART_COMMUNICATION_ALARM_OUI_SC":{},"SMART_ERROR_UNKNOWN":{},"SMART_HIGH_START_TEMPERATURE":{},"SMART_INVALID_CONFIGURATION_ERROR":{},"SMART_NO_START_TEMPERATURE":{},"SMART_READ_FLASH_ERROR":{},"SOFTWARE_COMPATIBILITY_CODE_ALARM":{},"STEAM_MAGNETRON_NTC":{},"TOO_HIGH_TEMPERATURE_ALARM":{},"TOUCHSCREEN_DRIVER_ALARM":{},"TOUCH_KEY_1_ALARM":{},"TOUCH_KEY_ALARM":{},"TRIAC_ALARM":{},"UNKNOWN_STATE_ERROR":{},"USB_CAMERA_DISCONNECTED_ALARM":{},"WATER_LEVEL_SENSOR_IN_STEAMER_OUT_OF_RANGE_ALARM":{},"WATER_LEVEL_SENSOR_IN_STEAM_TANK_DRAWER_OUT_OF_RANGE_ALARM":{},"WIFI_SIGNAL_MISS_ALARM":{}}},"applianceState":{"access":"read","triggers":[{"action":{"executeCommand":{"access":"write","values":{"STOPRESET":{}}}},"condition":{"operand_1":"value","operand_2":"RUNNING","operator":"eq"}},{"action":{"executeCommand":{"access":"write","values":{"STOPRESET":{}}}},"condition":{"operand_1":"value","operand_2":"PAUSED","operator":"eq"}},{"action":{"executeCommand":{"access":"write","values":{"START":{}}}},"condition":{"operand_1":"value","operand_2":"READY_TO_START","operator":"eq"}},{"action":{"$self":{"access":"read"}},"condition":{"operand_1":"value","operand_2":"ALARM","operator":"eq"}},{"action":{"executeCommand":{"access":"write","values":{"STOPRESET":{}}}},"condition":{"operand_1":"value","operand_2":"DELAYED_START","operator":"eq"}},{"action":{"executeCommand":{"access":"write","values":{"START":{}}}},"condition":{"operand_1":"value","operand_2":"END_OF_CYCLE","operator":"eq"}}],"type":"string","values":{"ALARM":{},"DELAYED_START":{},"END_OF_CYCLE":{},"IDLE":{},"OFF":{},"PAUSED":{},"READY_TO_START":{},"RUNNING":{}}},"cavityLight":{"access":"readwrite","type":"boolean","values":{"OFF":{},"ON":{}}},"displayFoodProbeTemperatureC":{"access":"read","type":"temperature"},"displayTemperatureC":{"access":"read","type":"temperature"},"doorState":{"access":"read","type":"string","values":{"CLOSED":{},"OPEN":{}}},"executeCommand":{"access":"write","type":"string","values":{"OFF":{},"ON":{},"RESUME":{},"START":{},"STOPRESET":{}}},"foodProbeInsertionState":{"access":"read","type":"string","values":{"INSERTED":{},"NOT_INSERTED":{}}},"networkInterface":{"linkQualityIndicator":{"access":"read","type":"string","values":{"EXCELLENT":{},"GOOD":{},"POOR":{},"UNDEFINED":{},"VERY_GOOD":{},"VERY_POOR":{}}},"otaState":{"access":"read","type":"string","values":{"DESCRIPTION_AVAILABLE":{},"DESCRIPTION_DOWNLOADING":{},"DESCRIPTION_READY":{},"FW_DOWNLOADING":{},"FW_DOWNLOAD_START":{},"FW_SIGNATURE_CHECK":{},"FW_UPDATE_IN_PROGRESS":{},"IDLE":{},"READY_TO_UPDATE":{},"UPDATE_ABORT":{},"UPDATE_CHECK":{},"UPDATE_ERROR":{},"UPDATE_OK":{},"WAITINGFORAUTHORIZATION":{}}},"swVersion":{"access":"read","type":"string"}},"program":{"access":"readwrite","type":"string","values":{"AUGRATIN":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":230,"disabled":false,"max":230,"min":80,"step":5,"type":"temperature"}},"BOTTOM":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":150,"disabled":false,"max":230,"min":80,"step":5,"type":"temperature"}},"BREAD_BAKING":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":180,"disabled":false,"max":230,"min":80,"step":5,"type":"temperature"}},"CLEAN_DESCALING":{"disabled":true},"CLEAN_DRYING":{"disabled":true},"CONVENTIONAL_COOKING":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":200,"disabled":false,"max":230,"min":30,"step":5,"type":"temperature"}},"DEFROST":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":40,"disabled":false,"max":40,"min":40,"type":"temperature"}},"DOUGH_PROVING":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":35,"disabled":false,"max":35,"min":35,"type":"temperature"}},"DRYING":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":100,"min":50,"step":5,"type":"temperature"}},"FROZEN_FOOD":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":220,"disabled":false,"max":230,"min":80,"step":5,"type":"temperature"}},"FULL_STEAM":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":90,"disabled":false,"max":100,"min":50,"step":5,"type":"temperature"}},"GRILL":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":200,"disabled":false,"max":230,"min":80,"step":5,"type":"temperature"}},"GRILL_FAN":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":200,"disabled":false,"max":230,"min":80,"step":5,"type":"temperature"}},"HUMIDITY_HIGH":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":90,"disabled":false,"max":130,"min":50,"step":5,"type":"temperature"}},"HUMIDITY_LOW":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":180,"disabled":false,"max":230,"min":50,"step":5,"type":"temperature"}},"HUMIDITY_MEDIUM":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":170,"disabled":false,"max":200,"min":50,"step":5,"type":"temperature"}},"KEEP_WARM":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":80,"disabled":false,"max":80,"min":80,"type":"temperature"}},"MOIST_FAN_BAKING":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":160,"disabled":false,"max":230,"min":90,"step":5,"type":"temperature"}},"PIZZA":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":200,"disabled":false,"max":230,"min":80,"step":5,"type":"temperature"}},"PLATE_WARMING":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":70,"disabled":false,"max":70,"min":70,"type":"temperature"}},"PRESERVING":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":160,"disabled":false,"max":170,"min":100,"step":5,"type":"temperature"}},"SLOW_COOK":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":90,"disabled":false,"max":150,"min":80,"step":5,"type":"temperature"}},"SOUS_VIDE":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":70,"disabled":false,"max":95,"min":50,"step":1,"type":"temperature"}},"STEAMIFY":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":180,"disabled":false,"max":230,"min":50,"step":5,"type":"temperature"}},"STEAM_CLEAN_INTENSE":{"disabled":true},"STEAM_CLEAN_LIGHT":{"disabled":true},"STEAM_CLEAN_RINSING":{"disabled":true},"STEAM_REGENERATING":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":110,"disabled":false,"max":130,"min":80,"step":5,"type":"temperature"}},"TRUE_FAN":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetFoodProbeTemperatureC":{"access":"readwrite","default":60,"disabled":false,"max":99,"min":30,"step":1,"type":"temperature"},"targetTemperatureC":{"access":"readwrite","default":150,"disabled":false,"max":230,"min":30,"step":5,"type":"temperature"}},"YOGHURT":{"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","disabled":false,"max":86340,"min":0,"step":60,"values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","disabled":false,"max":86340,"min":0,"step":60},"targetTemperatureC":{"access":"readwrite","default":42,"disabled":false,"max":42,"min":42,"type":"temperature"}}}},"remoteControl":{"access":"read","type":"string","values":{"DISABLED":{},"ENABLED":{},"NOT_SAFETY_RELEVANT_ENABLED":{},"TEMPORARY_LOCKED":{}}},"runningTime":{"access":"read","default":0,"type":"number"},"startTime":{"access":"readwrite","default":"INVALID_OR_NOT_SET_TIME","max":86340,"min":0,"step":60,"type":"number","values":{"INVALID_OR_NOT_SET_TIME":{"disabled":true}}},"targetDuration":{"access":"readwrite","max":86340,"min":0,"step":60,"type":"number"},"targetFoodProbeTemperatureC":{"access":"readwrite","type":"temperature"},"targetMicrowavePower":{"access":"readwrite","type":"number"},"targetTemperatureC":{"access":"readwrite","type":"temperature"},"timeToEnd":{"access":"read","type":"number"},"waterTankEmpty":{"access":"read","type":"string","values":{"STEAM_TANK_EMPTY":{},"STEAM_TANK_FULL":{}}},"waterTrayInsertionState":{"access":"read","type":"string","values":{"INSERTED":{},"NOT_INSERTED":{}}}}



man. 16. sep. 2024 kl. 22:25 skrev GSlender ***@***.***>:

**Comment by gslender** [comment]
This might just be how the oven works. Running time in the json your provided is just currently the valuye '-1' and so I'm not sure what value it would be during operations, if it never updates then it will always show as blank. Running time is how long the oven has been going. Does the AEG/Electrolux iOS app actually have a end time value shown?

**Comment by Heha16** [comment]
Hi
Looks like its just shutdown tile in the app and not the ordinary countdown
clock.

Thank you for quick help

man. 16. sep. 2024 kl. 23:45 skrev GSlender ***@***.***>:
