### ISSUE TITLE
New Device: <AEG Robotstofzuiger CLEAN 6000>

### ISSUE THREAD

**Issue by robberti4y87** [gslender/com.electrolux-aeg.ocp#15]
Please add the AEG Robotstofzuiger CLEAN 6000, see here link to AEG website for this robot vacuum cleaner :https://www.aeg.nl/home-comfort/vacuum-cleaners/robotic-vacuum-cleaners/robotic-vacuum-cleaner/ar61ud1ug/

See here the JSON: 

{"applianceId":"900402070346010111139298","applianceData":{"applianceName":"Robotstofzuiger🥳","created":"2024-08-11T21:12:45.7094485Z","modelName":"700series"},"properties":{"desired":{"TimeZoneStandardName":"Europe/Amsterdam","enableLiveMaps":false,"LocationReq":true,"TimeZoneDaylightRule":":GMT+1:GMT+2:0100:(1900)040102-0:110103-0","tasks":{"0":{"start":{"time":"01:00:56","properties":{"waterPumpRate":"off","vacuumMode":"standard","cleaningCommand":"startGlobalClean"},"weekDays":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]},"enabled":true,"Name":"Dagelijkse schoonmaak"}},"$metadata":{"$lastUpdated":"2024-09-23T21:42:18.4362332Z","$lastUpdatedVersion":104,"TimeZoneStandardName":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92},"enableLiveMaps":{"$lastUpdated":"2024-09-23T21:42:18.4362332Z","$lastUpdatedVersion":104},"LocationReq":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92},"TimeZoneDaylightRule":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92},"tasks":{"0":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92,"start":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92,"time":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92},"properties":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92,"waterPumpRate":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92},"vacuumMode":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92},"cleaningCommand":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92}},"weekDays":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92}},"enabled":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92},"Name":{"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92}},"$lastUpdated":"2024-09-23T20:11:38.7643556Z","$lastUpdatedVersion":92}},"$version":104},"reported":{"VmNo_NIU":"VM214_T_03.13.12_MIDAS_GD","VmNo_MCU":"VM220_T_03.05.82_MIDAS","capabilities":{},"tasks":{"0":{"enabled":true,"start":{"properties":[{"waterPumpRate":"off"},{"vacuumMode":"standard"},{"cleaningCommand":"startGlobalClean"}],"time":"01:00:56","weekDays_mask":127}}},"batteryStatus":38,"cleaningMode":"notSet","state":"idle","faultCode":"charging","chargingStatus":"charging","vacuumMode":"standard","waterPumpRate":"medium","binTank":"dustBox","mopInstalled":false,"upgradeState":"idle","upgradeProgress":0,"niuStatus":"available","$metadata":{"$lastUpdated":"2024-09-23T20:22:42.574Z","VmNo_NIU":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"VmNo_MCU":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"capabilities":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"tasks":{"0":{"$lastUpdated":"2024-09-23T20:11:38.9629053Z","enabled":{"$lastUpdated":"2024-09-23T20:11:38.9629053Z"},"start":{"$lastUpdated":"2024-09-23T20:11:38.9629053Z","properties":{"$lastUpdated":"2024-09-23T20:11:38.9629053Z"},"time":{"$lastUpdated":"2024-09-23T20:11:38.9629053Z"},"weekDays_mask":{"$lastUpdated":"2024-09-23T20:11:38.9629053Z"}}},"$lastUpdated":"2024-09-23T20:11:38.9629053Z"},"batteryStatus":{"$lastUpdated":"2024-09-23T21:41:28.8406026Z"},"cleaningMode":{"$lastUpdated":"2024-09-23T20:22:42.6467602Z"},"state":{"$lastUpdated":"2024-09-23T20:22:42.6467602Z"},"faultCode":{"$lastUpdated":"2024-09-23T20:22:41.8342665Z"},"chargingStatus":{"$lastUpdated":"2024-09-23T20:22:41.8342665Z"},"vacuumMode":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"waterPumpRate":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"binTank":{"$lastUpdated":"2024-09-23T20:20:19.1182431Z"},"mopInstalled":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"upgradeState":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"upgradeProgress":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"niuStatus":{"$lastUpdated":"2024-09-16T17:54:54.8422726Z"},"cleaningStarted":{"$lastUpdated":"2024-09-23T20:21:50.493Z"},"transform":{"$lastUpdated":"2024-09-23T20:11:30.926Z"},"cleanSize":{"$lastUpdated":"2024-09-23T19:47:26.41Z"},"cleanTime":{"$lastUpdated":"2024-09-23T20:19:20.312Z"},"session":{"$lastUpdated":"2024-09-23T20:22:42.574Z"}},"$version":3109,"deviceId":"900402070346010111139298","cleaningStarted":{"id":"48350a29-1e25-e4bf-4502-ac04f59d5c3d","cleaningMode":"returnToCharger","reason":"ui","startTime":"2024-09-23T20:21:48Z"},"transform":{"sessionId":"e2dcfcef-6f3c-6bc0-65da-992c7c4c03ba","position":{"x":72,"y":58},"angle":-2.854},"cleanSize":6406,"cleanTime":0,"session":{"id":"48350a29-1e25-e4bf-4502-ac04f59d5c3d","startTime":"2024-09-23T20:21:48Z","endTime":"2024-09-23T20:22:41Z","duration":0,"cleanSize":6406,"vacuumMode":"standard","cleaningMode":"returnToCharger","waterPumpRate":"medium","mopInstalled":false,"faultCode":"charging","pitstopCount":0,"finishState":"finishedInCharger","reason":"ui"}},"metadata":null},"status":"enabled","connectionState":"Connected"}

Apparaatmogelijkheden

{"batteryStatus":{"access":"read","max":100,"min":1,"type":"int"},"binTank":{"access":"read","type":"string","values":{"dustBox":{},"none":{}}},"chargingStatus":{"access":"read","type":"string","values":{"charging":{},"fullyCharged":{},"idle":{}}},"cleaningCommand":{"access":"readwrite","schedulable":true,"type":"string","values":{"pauseClean":{},"resumeClean":{},"startEdgeClean":{},"startGlobalClean":{},"startGoToCharger":{},"startPointClean":{},"stopClean":{}}},"cleaningMode":{"access":"read","type":"string","values":{"edgeClean":{},"globalClean":{},"notSet":{},"pointClean":{},"returnToCharger":{}}},"faultCode":{"access":"read","type":"string","values":{"batteryLowPercentage":{},"batteryNotChargedEnough":{},"canNotCharge":{},"canNotChargeOfLowVoltage":{},"canNotFindCharger":{},"dustbinNotInPlace":{},"frontJammedOrCollisionSensorDirty":{},"isOnUnevenSurface":{},"noFault":{},"rollerBrushStuck":{},"stuckFailedToEscape":{},"stuckOfCliffSensor":{}}},"findMe":{"access":"readwrite"},"state":{"access":"read","type":"string","values":{"goingHome":{},"idle":{},"inProgress":{},"paused":{},"sleeping":{}}},"vacuumMode":{"access":"readwrite","schedulable":true,"type":"string","values":{"energySaving":{},"maxPower":{},"powerful":{},"quiet":{},"standard":{}}}}

**Comment by gslender** [comment]
Added in the test release published
https://homey.app/en-au/app/com.electrolux-aeg.ocp/Electrolux-AEG/test/

**Comment by robberti4y87** [comment]
Thanks!!

**Comment by robberti4y87** [comment]
I do get the error 'Missing Capability Listener: cleaning_command' by every command. Did I do something wrong by adding the device?

**Comment by gslender** [comment]
Fixed in v1.4.15 that was released to production !!
