### ISSUE TITLE
A9 Purifier lost connection 

### ISSUE THREAD

**Issue by ycagwyn** [gslender/com.electrolux-aeg.ocp#17]
Hi.

I'm getting "Device is unavailable.." from my newly added A9 Air purifier with these settings:

{"applianceId":"950011385850004525087076","applianceData":{"applianceName":"Luftrenaren","created":"2024-09-27T10:57:15.4222819Z","modelName":"PUREA9"},"properties":{"desired":{"TimeZoneStandardName":"Europe/Stockholm","LocationReq":true,"TimeZoneDaylightRule":":GMT+1:GMT+2:0100:(1900)040102-0:110103-0","$metadata":{"$lastUpdated":"2024-09-27T10:57:27.0124121Z","$lastUpdatedVersion":3,"TimeZoneStandardName":{"$lastUpdated":"2024-09-27T10:57:27.0124121Z","$lastUpdatedVersion":3},"LocationReq":{"$lastUpdated":"2024-09-27T10:57:27.0124121Z","$lastUpdatedVersion":3},"TimeZoneDaylightRule":{"$lastUpdated":"2024-09-27T10:57:27.0124121Z","$lastUpdatedVersion":3}},"$version":3},"reported":{"ErrPM2_5":false,"ErrTVOC":false,"ErrTempHumidity":false,"ErrFanMtr":false,"ErrCommSensorDisplayBrd":false,"DoorOpen":false,"FilterRFID":"1D277074580000","FilterLife":13,"Workmode":"Auto","Fanspeed":2,"UILight":true,"SafetyLock":false,"Ionizer":false,"FilterType":96,"DspIcoPM2_5":true,"DspIcoPM1":true,"DspIcoPM10":true,"DspIcoTVOC":true,"tasks":{},"logE":3103,"logW":454,"InterfaceVer":20230110,"VmNo_NIU":"VM185_A_03.00.01_ELYSIAN","TVOCBrand":"AMS","FrmVer_NIU":"3.0.1","capabilities":{"tasks":{}},"SignalStrength":"FAIR","$metadata":{"$lastUpdated":"2024-09-27T10:57:55.132Z","ErrPM2_5":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"ErrTVOC":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"ErrTempHumidity":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"ErrFanMtr":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"ErrCommSensorDisplayBrd":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"DoorOpen":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"FilterRFID":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"FilterLife":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"Workmode":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"Fanspeed":{"$lastUpdated":"2024-09-27T10:57:33.9440109Z"},"UILight":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"SafetyLock":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"Ionizer":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"FilterType":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"DspIcoPM2_5":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"DspIcoPM1":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"DspIcoPM10":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"DspIcoTVOC":{"$lastUpdated":"2024-09-27T10:57:27.8815436Z"},"tasks":{"$lastUpdated":"2024-09-27T10:57:17.8641876Z"},"logE":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z"},"logW":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z"},"InterfaceVer":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z"},"VmNo_NIU":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z"},"TVOCBrand":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z"},"FrmVer_NIU":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z"},"capabilities":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z","tasks":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z"}},"SignalStrength":{"$lastUpdated":"2024-09-27T10:57:27.9752257Z"},"ECO2":{"$lastUpdated":"2024-09-27T10:57:55.132Z"},"RSSI":{"$lastUpdated":"2024-09-27T10:57:55.132Z"},"PM1":{"$lastUpdated":"2024-09-27T10:57:28.225Z"},"PM2_5":{"$lastUpdated":"2024-09-27T10:55:29.346Z"},"Humidity":{"$lastUpdated":"2024-09-27T10:55:29.346Z"},"PM10":{"$lastUpdated":"2024-09-27T10:57:31.585Z"},"Temp":{"$lastUpdated":"2024-09-27T10:55:29.346Z"},"TVOC":{"$lastUpdated":"2024-09-27T10:57:17.803Z"}},"$version":9,"deviceId":"950011385850004525087076","ECO2":645,"RSSI":-66,"PM1":2,"PM2_5":1,"Humidity":65,"PM10":4,"Temp":20,"TVOC":38},"metadata":null},"status":"enabled","connectionState":"Connected"}

What can I do to make it communicate?

**Comment by ycagwyn** [comment]
Diagnostic report is e1a46bc6-4ef5-4867-9c7a-cbf345507913

**Comment by FredStang** [comment]
Samme here

**Comment by gslender** [comment]
fixed in latest release v1.4.14

**Comment by ycagwyn** [comment]
Thank you so much, it works perfectly now
