### ISSUE TITLE
Add info to washing machine app

### ISSUE THREAD

**Issue by nesheimt** [gslender/com.electrolux-aeg.ocp#19]
Hi
Thanks for providing this app! When time allows could you please add the «parameter» to the «device card» that shows if the washing machine needs detergent and softener to the AutoDose system?

If not to much hazzle info like program and temperatur would be great (but not important) to add to my kitchen-smart touch screen using ioBroker for GUI.
![image](https://github.com/user-attachments/assets/1450384b-3bce-4075-aaa6-8d9f9db89a7f)

**Comment by gslender** [comment]
I'll need you to provide the state and capabilities JSON 

As I don't know what variables these would be - same with Program and Temperature (even though it may seem obvious) - with the json I would only be guessing

**Comment by gslender** [comment]
Closing as there is no further input from the user

**Comment by nesheimt** [comment]
I’m out travelling for a while…back this weekend. Since «everything» goes on inside your app, is there ant way to «extract» this capablity and state JSON?
