### ISSUE TITLE
Electrolux Comfort 600 Portabel AC BTU 12000 

### ISSUE THREAD

**Issue by Granath67** [gslender/com.electrolux-aeg.ocp#2]
Hi!
Earlier I have installed HomeyPro App “Electrolux Wellbeing” and tried to find some tips, code anything to help me find a way to control the AC with the Homey. I found this codes to another automation platform if it to any help.
https://hub.docker.com/r/dannyyy/electrolux-mqtt
https://github.com/dannyyy/electrolux_mqtt
I’m not a coder myself.. 😊
I have a Electrolux Comfort 600 Portabel AC BTU 12000 witch I would love to have the opportunity to control it with Homey Pro.

/ Magnus

**Comment by gslender** [comment]
Please follow the instructions on the readme page to add an unsupported device
