### ISSUE TITLE
Missing Flow cards for dryer

### ISSUE THREAD

**Issue by Cupra1979** [gslender/com.electrolux-aeg.ocp#3]
Hi there!

First of all, thanks for the app, even though it is new, it is very promising!

After logging in, I succesfully added my Electrolux dryer to Homey and I can see status, time to end, cycle etc...but when I try to create an advanced flow for receiving a notification when the cycle is finished, I cannot find any card available.
I have a generic "The Cycle phase has changed" but it seems not linked to my device and I cannot select the status change.
Do you plan to add more cards? It would be sufficient something related to the status change (from "drying" to "off") or to the Time to End (when zero, then create notification).

Thanks a lot in advance!!

**Comment by gslender** [comment]
Yes, working on adding some When (condition) cards

**Comment by gslender** [comment]
Note that 

- CyclePhase reports these values... 
"ANTICREASE": {},
            "COOL": {},
            "CYCLE_PHASE_HIDDEN": {},
            "DRY": {},
            "UNAVAILABLE": {}
- ApplianceState reports these values... 
"ALARM": {},
            "DELAYED_START": {},
            "END_OF_CYCLE": {},
            "IDLE": {},
            "OFF": {},
            "PAUSED": {},
            "READY_TO_START": {},
            "RUNNING": {}

**Comment by gslender** [comment]
I've almost got this sorted... it looks like being done like this...

<img width="636" alt="image" src="https://github.com/user-attachments/assets/bd2f6370-7505-457f-9dcd-82a0e12c59cd">

**Comment by gslender** [comment]
Try this test version of the app, which will soon be published
https://homey.app/en-au/app/com.electrolux-aeg.ocp/Electrolux-AEG/test/
