### ISSUE TITLE
Data not available since 1.3.4

### ISSUE THREAD

**Issue by andiwirz** [gslender/com.electrolux-aeg.ocp#4]
Since version 1.3.4 - I do not have any values in the app:

![image](https://github.com/user-attachments/assets/5c0a5108-1845-4681-ad25-e2c226610195)

Already tried to uninstall, install and restart the app - As well remove and readd the Air Purifier

Controlling the appliance is still possible.

If you need the diagnose data: e3ba3ec0-1b7d-4eb0-a337-5a4d1e230f76

**Comment by gslender** [comment]
A property I am requesting must be incorrect, so can you send me the **Appliance State {json}** and **Appliance Capabilities {json}** files that are published in the device Advanced Settings. Include these two data files in your reply below.

For example:

```
2024-06-28T03:07:51.553Z [log] [ElectroluxAEGApp] [{"applianceId":"XXXXXXXX_01:xxxxxxx-xxxxxx","applianceData":{"applianceName":"Dryer","created":"2024-06-25T06:35:21.260Z","modelName":"TD"},"properties":{"desired":{},"reported":{"doorState":"OPEN","timeToEnd":-1,"networkInterfaceAlwaysOn":"ON","miscellaneous":{},"applianceUiSwVersion":"URDB0A3H","applianceTotalWorkingTime":7200,"remoteControl":"NOT_SAFETY_RELEVANT_ENABLED","dryingNominalLoadWeight":65535,

        <<SNIP WE'VE SHORTENED THIS FOR THE EXMAPLE, PLUS PLEASE KEEP THE ENTIRE JSON IN YOUR COPY/PASTE>>

"tDEconomy_Eco":false,"tDEconomy_Quick":false,"refresh":false,"dryingTime":65535,"memoryId":20,"programUID":"MACHINE_SETTINGS_HIDDEN_TEST","antiCreaseValue":255,"tDEconomy_Night":false},"cycleMemory1":{"reversePlus":false,"tDEconomy_Eco":false,"tDEconomy_Quick":false,"refresh":false,"dryingTime":65535,"memoryId":30,"programUID":"MACHINE_SETTINGS_HIDDEN_TEST","antiCreaseValue":255,"tDEconomy_Night":false}},"metadata":{}},"status":"enabled","connectionState":"connected"}]
```

**Comment by gslender** [comment]
Have pushed out v1.3.5 as I think I found the bug and squashed it !!

**Comment by Tebitcz** [comment]
I have the same issue even with 1.3.5. versiom
7040212c-bd93-4097-a8e6-b843c73e1bc7

**Comment by gslender** [comment]
Found another bug and so v1.3.6 might be the charm !!

**Comment by gslender** [comment]
Closing as you've not replied

**Comment by andiwirz** [comment]
Sorry for not replying - issue is solved

Thank you!
