### ISSUE TITLE
New Device: Airpurifyer 500 Electrolux 

### ISSUE THREAD

**Issue by brohl65** [gslender/com.electrolux-aeg.ocp#5]
Hi
I have installed the app and I can see my airpurifyer but I am missing some data as per attached picture. 
can you help or add the support for this?

I do not know how to copy the requested code you want so I made a picture of the issues and the 2 codes. 

![IMG_0643](https://github.com/user-attachments/assets/b46e6879-6c84-492c-9f6c-5317483644d2)
![IMG_0644](https://github.com/user-attachments/assets/64dc2557-9acc-4cb9-a48c-2485015d713d)
![IMG_0645](https://github.com/user-attachments/assets/a291641e-8810-429d-b9a8-cfb2461daed1)

// Björn ### 

To request a new device, install the Electrolux/AEG OCP Homey App

Add your email and password to the app Configure settings.

Then add a New Device, choose the Electrolux/AEG OCP app Brand, and choose the Unknown device and if you have any appliance, it should be found and added. 

I will need the Appliance State {json} and Appliance Capabilities {json} files that are published in the device Advanced Settings when you install the Unknown device. Include these two data files in your submission below.

Without this information, we cannot add support for your device, and the issue will be closed.

For example:

```
2024-06-28T03:07:51.553Z [log] [ElectroluxAEGApp] [{"applianceId":"XXXXXXXX_01:xxxxxxx-xxxxxx","applianceData":{"applianceName":"Dryer","created":"2024-06-25T06:35:21.260Z","modelName":"TD"},"properties":{"desired":{},"reported":{"doorState":"OPEN","timeToEnd":-1,"networkInterfaceAlwaysOn":"ON","miscellaneous":{},"applianceUiSwVersion":"URDB0A3H","applianceTotalWorkingTime":7200,"remoteControl":"NOT_SAFETY_RELEVANT_ENABLED","dryingNominalLoadWeight":65535,

        <<SNIP WE'VE SHORTENED THIS FOR THE EXMAPLE, PLUS PLEASE KEEP THE ENTIRE JSON IN YOUR COPY/PASTE>>

"tDEconomy_Eco":false,"tDEconomy_Quick":false,"refresh":false,"dryingTime":65535,"memoryId":20,"programUID":"MACHINE_SETTINGS_HIDDEN_TEST","antiCreaseValue":255,"tDEconomy_Night":false},"cycleMemory1":{"reversePlus":false,"tDEconomy_Eco":false,"tDEconomy_Quick":false,"refresh":false,"dryingTime":65535,"memoryId":30,"programUID":"MACHINE_SETTINGS_HIDDEN_TEST","antiCreaseValue":255,"tDEconomy_Night":false}},"metadata":{}},"status":"enabled","connectionState":"connected"}]
```

Finally, please link to more information about the device, e.g. the manufacturer's website to assist with images and icons that will be needed to complete the app update and publish in the app store.

**Comment by gslender** [comment]
>I do not know how to copy the requested code you want so I made a picture of the issues and the 2 codes.

Unfortunately, unless you can copy/paste these json data text to me, I cannot help you.

The process is really easy and you may find copy/paste works better when viewing Homey via the web - https://my.homey.app/

**Comment by brohl65** [comment]
Ok great I will try. 
I however have another issue now (maybe because I am new to this) but I deleted the air purifier and reinstalled it and now there is no one to find in the app???
I have deleted and reinstalled all apps and hardware but still I can only find the purifier as a “other” and not as the icon. This “other” has nothing … just working and flows…

does homey remember a deleted unit or??

is there a way to “find” my purifier again?

thx in advance
Björn

**Comment by gslender** [comment]
Yep, I'll need those json data files to confirm exactly how to correctly add support for your device. Once you send me these I will be able to quickly add support for exactly your appliances.

**Comment by brohl65** [comment]
Hi
Will do

but do you know the reason why it does not show again as a purifier? I can only add it now as an “other device”??

**Comment by gslender** [comment]
Yes I do. It has occurred because I've forced the app to only create Pure devices I have json data files that detail the necessary information. Before it allowed any AEG/Electrolux device to be added as a Pure even though it wasn't one.


Send me the json and I'll be able to fix this for you with an update to the app.

**Comment by brohl65** [comment]
And this is now from “other” :) 

Bjorn

**Comment by gslender** [comment]
Try this test version and let me know if this works...

https://homey.app/en-au/app/com.electrolux-aeg.ocp/Electrolux-AEG/test/

**Comment by brohl65** [comment]
Testing now

**Comment by brohl65** [comment]
Ok
Did not maybe work as intended or you wanted to have this error message :)
![IMG_0652](https://github.com/user-attachments/assets/ce1a85d7-3a62-4236-82a5-fb1fb0e5406c)

Björn

**Comment by brohl65** [comment]
If I try “other/unknown” it still shows up but not when I choose an air purifier then I get the previous error message!
![IMG_0653](https://github.com/user-attachments/assets/8a0a8075-1563-416a-bb54-0dcd56652760)

//Björn

**Comment by gslender** [comment]
A new test was pushed up to hopefully fix this for you - your model Electrolux/AEG appliance is fairly different to the normal OneConnected devices - must be either old, or something they bought and haven't updated the API

Version 1.4.3 should fix it

https://homey.app/en-au/app/com.electrolux-aeg.ocp/Electrolux-AEG/test/

**Comment by brohl65** [comment]
Just as info. 
the unit is brand NEW from Electrolux and i have had it for 2 weeks!
I will try your new version again and see. 

It worked the first time I used the 1.3.6 but had to delete it and reinstall and then it will not find it. 

Thanks anyway :)
Björn

**Comment by brohl65** [comment]
Update

I just tried the last version you supplied and it found it again :)
Now it looks like this and I also have some values :)
Thanks mate
Björn 
![IMG_0659](https://github.com/user-attachments/assets/80bb30b5-35b3-47d4-b97b-2cf3820e22cd)
![IMG_0658](https://github.com/user-attachments/assets/4ae2aba5-2c00-4873-8589-a3491e2be20c)
