### ISSUE TITLE
Remote access status oven 

### ISSUE THREAD

**Issue by cscheiene** [gslender/com.electrolux-aeg.ocp#6]
Is it possible to see the remote access status on the oven from the api?

Remote access/start can manually be enabled or disabled on the oven display. And if the oven is not used for a long time, remote access is automatically disabled due to safety reason.

When remote access is disabled you can only read status, turn on the lights etc. But can't start the oven remotely.

This information is available in the Aeg mobile app, and would be nice to see in homey app as well. Maybe turn the main tile "off" when remote start is disable and some information of the status within the device.

**Comment by gslender** [comment]
Latest test v1.3.9 has been updated with this feature.

https://homey.app/a/com.electrolux-aeg.ocp/test/

**Comment by cscheiene** [comment]
Thanks for the quick response. Just tested, it shows wifi status. But not if remote access/start is enabled. See pictures from the Aeg mobile app. There are two status icons, wifi and remote access
![Screenshot_20240824_090817](https://github.com/user-attachments/assets/b6fd6d63-c92f-4a46-a752-e995f232822e)
![Screenshot_20240824_090801_com electrolux oneapp android aeg](https://github.com/user-attachments/assets/69d5e5bd-50a8-4fb7-9ff8-0bd6f27c342d)

**Comment by cscheiene** [comment]
![Screenshot_20240824_085327_com electrolux oneapp android aeg_edit_277074310979075](https://github.com/user-attachments/assets/63805234-6a2a-4d54-a969-d22c4702bc11)
![Screenshot_20240824_090817](https://github.com/user-attachments/assets/e28b76ee-0d53-4bcb-9c36-7d6698398920)

**Comment by gslender** [comment]
Okay, I found the property you want enabled. Give me 30 mins.

**Comment by gslender** [comment]
v1.4.1 in Test should be what you are looking for

**Comment by cscheiene** [comment]
Yes it it is. But only "Enabled" and "Temporary Locked" works. When disabled, it still show Enabled in the Homey app.

Temporary Locked is when it is enabled, but the door is open so it wont start.

**Comment by cscheiene** [comment]
When looking at the device status:

If remote access is disabled manually on the oven is says: "remoteControl\":\"NOT_SAFETY_RELEVANT_ENABLED\" This displays as OFF in the AEG Mobile APP
If enabled: "remoteControl\":\"ENABLED\" This display as ON the the AEG mobile app.

Both display as ENABLED in the Homey app.

Remote access can also be automatically disabled if the oven is not used for 24 hours. I'm not able to check the status for this yet.

**Comment by gslender** [comment]
LOL 😂 yep that's my fault

I saw that long worded enabled and shortened it to just Enabled, but you interpret that as essentially disabled. So what's a shorter way of saying this? Safety Enabled?

**Comment by cscheiene** [comment]
Yes, or maybe just say Disabled. Because remote access is disabled and you cant remotely control it.
The AEG mobile app just says remote access off when this status is active

**Comment by gslender** [comment]
Latest test has the swap

**Comment by cscheiene** [comment]
Works great, thanks for great support.
