### ISSUE TITLE
Remote access on/off

### ISSUE THREAD

**Issue by cscheiene** [gslender/com.electrolux-aeg.ocp#7]
Thanks for the quick response. Just tested, it shows wifi status. But not if remote access/start is enabled. See pictures from the Aeg mobile app. There are two status icons, wifi and remote access. Remote access shows on/off (på/av)

_Originally posted by @cscheiene in https://github.com/gslender/com.electrolux-aeg.ocp/issues/6#issuecomment-2308160953_

**Comment by cscheiene** [comment]
![Screenshot_20240824_090817](https://github.com/user-attachments/assets/fe78fe2c-a942-486d-9876-c5ad7f6b936c)
![Screenshot_20240824_085327_com electrolux oneapp android aeg_edit_277074310979075](https://github.com/user-attachments/assets/621eec38-612e-4d62-9c39-34811522300d)

**Comment by cscheiene** [comment]
Closed by mistake

**Comment by cscheiene** [comment]
Closed by mistake

**Comment by gslender** [comment]
I will reopen the original issue
