### ISSUE TITLE
Possible bug when a '#' is part of the password

### ISSUE THREAD

**Issue by tutu81** [gslender/com.electrolux-aeg.ocp#8]
Hello, 

First of all thanks for this great apps. I'm using it for a Pure A9 air filter. 

My issue: my password contains a # as special char. When I login via the apps, I got a message that my email /  password is invalid. 
By changing the password and replacing the '#' with a '_' it works.

Could it be that it is a kind of bug?

**Comment by gslender** [comment]
I cannot see anything in the code that would care what the content of the password is - I also tested by changing my password to contain a # within the pwd and that made no difference. I suspect the issue may have been just co-incidence and the backend by AEG/Electrolux just didn't have the pwd sequenced correct at the time.

Unless I can replicate (or you can and tell me the steps that repeatedly show that) I'm going to close this.
