### ISSUE TITLE
New Device: Comfort 600 Portabel AC BTU 12000

### ISSUE THREAD

**Issue by Granath67** [gslender/com.electrolux-aeg.ocp#9]
Hi Hope that I've done this right!
Appliance State 
{"applianceId":"950011606305020321110697","applianceData":{"applianceName":"AC","created":"2024-06-14T10:33:06.6662811Z","modelName":"Azul"},"properties":{"desired":{"TimeZoneStandardName":"Europe/Stockholm","VmNo_NIU":"VM211_A_03.48.07_AZUL","ReportedSleepModeLastUpdate":"2024-08-17T06:08:17.8505871Z","ReportedSleepModeLastValue":"off","TimeZoneDaylightRule":":GMT+1:GMT+2:0100:(1900)040102-0:110103-0","LocationReq":true,"$metadata":{"$lastUpdated":"2024-09-06T12:12:11.9221502Z","$lastUpdatedVersion":88,"TimeZoneStandardName":{"$lastUpdated":"2024-09-06T12:12:11.9221502Z","$lastUpdatedVersion":88},"VmNo_NIU":{"$lastUpdated":"2024-09-06T12:12:11.9221502Z","$lastUpdatedVersion":88},"ReportedSleepModeLastUpdate":{"$lastUpdated":"2024-09-06T12:12:11.9221502Z","$lastUpdatedVersion":88},"ReportedSleepModeLastValue":{"$lastUpdated":"2024-09-06T12:12:11.9221502Z","$lastUpdatedVersion":88},"TimeZoneDaylightRule":{"$lastUpdated":"2024-09-06T12:12:11.9221502Z","$lastUpdatedVersion":88},"LocationReq":{"$lastUpdated":"2024-09-06T12:12:11.9221502Z","$lastUpdatedVersion":88}},"$version":88},"reported":{"dataModelVersion":"1.0.1","VmNo_NIU":"VM211_A_03.48.07_AZUL","capabilities":{},"applianceState":"running","startTime":0,"stopTime":0,"temperatureRepresentation":"celsius","sleepMode":"off","targetTemperatureC":20,"uiLockMode":false,"mode":"cool","fanSpeedSetting":"auto","verticalSwing":"off","filterState":"good","VmNo_MCU":"V1.0.2","tasks":{},"logE":0,"logW":343,"schedulerSession":"off","upgradeState":"idle","schedulerMode":"off","$metadata":{"$lastUpdated":"2024-09-06T14:42:28.987Z","dataModelVersion":{"$lastUpdated":"2024-09-06T12:12:11.7053421Z"},"VmNo_NIU":{"$lastUpdated":"2024-09-06T12:12:11.7053421Z"},"capabilities":{"$lastUpdated":"2024-09-06T12:12:11.7053421Z"},"applianceState":{"$lastUpdated":"2024-09-06T13:33:33.185706Z"},"startTime":{"$lastUpdated":"2024-09-06T13:33:36.2325553Z"},"stopTime":{"$lastUpdated":"2024-09-06T13:33:36.2325553Z"},"temperatureRepresentation":{"$lastUpdated":"2024-09-06T13:33:36.0450514Z"},"sleepMode":{"$lastUpdated":"2024-09-06T13:33:35.2794308Z"},"targetTemperatureC":{"$lastUpdated":"2024-09-06T13:33:35.8419816Z"},"uiLockMode":{"$lastUpdated":"2024-09-06T13:33:35.6544379Z"},"mode":{"$lastUpdated":"2024-09-06T13:33:34.9200504Z"},"fanSpeedSetting":{"$lastUpdated":"2024-09-06T13:33:35.0919409Z"},"verticalSwing":{"$lastUpdated":"2024-09-06T13:33:35.4669287Z"},"filterState":{"$lastUpdated":"2024-09-06T13:33:34.170054Z"},"VmNo_MCU":{"$lastUpdated":"2024-09-06T13:33:36.4200622Z"},"tasks":{"$lastUpdated":"2024-06-14T10:33:10.7237697Z"},"logE":{"$lastUpdated":"2024-09-06T12:12:11.7053421Z"},"logW":{"$lastUpdated":"2024-09-06T12:12:11.7053421Z"},"schedulerSession":{"$lastUpdated":"2024-09-06T13:33:35.4669287Z"},"upgradeState":{"$lastUpdated":"2024-09-04T12:06:30.1664594Z"},"schedulerMode":{"$lastUpdated":"2024-09-04T12:06:30.2905815Z"},"ambientTemperatureC":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"compressorState":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"totalRuntime":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"compressorCoolingRuntime":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"compressorHeatingRuntime":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"filterRuntime":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"networkInterface":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"ambientTemperatureF":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"fourWayValveState":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"evapDefrostState":{"$lastUpdated":"2024-09-06T14:42:28.987Z"},"hepaFilterLifeTime":{"$lastUpdated":"2024-09-06T14:42:28.987Z"}},"$version":2759,"deviceId":"950011606305020321110697","ambientTemperatureC":21,"compressorState":"on","totalRuntime":2445146,"compressorCoolingRuntime":1265284,"compressorHeatingRuntime":0,"filterRuntime":586860,"networkInterface":{"linkQualityIndicator":"VERY_GOOD","rssi":-46},"ambientTemperatureF":null,"fourWayValveState":"off","evapDefrostState":"off","hepaFilterLifeTime":0},"metadata":null},"status":"enabled","connectionState":"Connected"}

Appliance Capabilities 
{"alerts":{"access":"read","type":"alert","values":{"COMMUNICATION_FAULT":{},"DC_MOTOR_FAULT":{},"DRAIN_PAN_FULL":{},"INDOOR_DEFROST_THERMISTOR_FAULT":{},"ROOM_TEMPERATURE_THERMISTOR_FAULT":{}}},"ambientTemperatureC":{"access":"read","step":1,"type":"int"},"applianceState":{"access":"read","type":"string","values":{"OFF":{},"RUNNING":{}}},"executeCommand":{"access":"readwrite","schedulable":true,"type":"string","values":{"OFF":{},"ON":{}}},"fanSpeedSetting":{"access":"readwrite","schedulable":true,"type":"string","values":{"AUTO":{},"HIGH":{},"LOW":{},"MIDDLE":{}}},"fanSpeedState":{"access":"read","type":"string","values":{"HIGH":{},"LOW":{},"MIDDLE":{}}},"mode":{"access":"readwrite","schedulable":true,"triggers":[{"action":{"fanSpeedSetting":{"access":"readwrite","type":"string","values":{"HIGH":{},"LOW":{},"MIDDLE":{}}},"sleepMode":{"disabled":true},"targetTemperatureC":{"access":"readwrite","default":23,"disabled":true,"max":23,"min":23,"step":1,"type":"temperature"}},"condition":{"operand_1":"value","operand_2":"FANONLY","operator":"eq"}},{"action":{"fanSpeedSetting":{"access":"read","type":"string","values":{"LOW":{}}},"sleepMode":{"disabled":true},"targetTemperatureC":{"access":"readwrite","default":23,"disabled":true,"max":23,"min":23,"step":1,"type":"temperature"}},"condition":{"operand_1":"value","operand_2":"DRY","operator":"eq"}},{"action":{"fanSpeedSetting":{"access":"read","type":"string","values":{"AUTO":{}}},"sleepMode":{"disabled":false},"targetTemperatureC":{"access":"readwrite","default":16,"max":32,"min":16,"step":1,"type":"temperature"}},"condition":{"operand_1":"value","operand_2":"AUTO","operator":"eq"}},{"action":{"fanSpeedSetting":{"access":"readwrite","type":"string","values":{"AUTO":{},"HIGH":{},"LOW":{},"MIDDLE":{}}},"sleepMode":{"disabled":false},"targetTemperatureC":{"access":"readwrite","default":16,"max":32,"min":16,"step":1,"type":"temperature"}},"condition":{"operand_1":"value","operand_2":"COOL","operator":"eq"}},{"action":{"fanSpeedSetting":{"access":"readwrite","type":"string","values":{"AUTO":{},"HIGH":{},"LOW":{},"MIDDLE":{}}},"sleepMode":{"disabled":false},"targetTemperatureC":{"access":"readwrite","default":16,"max":32,"min":16,"step":1,"type":"temperature"}},"condition":{"operand_1":"value","operand_2":"HEAT","operator":"eq"}}],"type":"string","values":{"AUTO":{},"COOL":{},"DRY":{},"FANONLY":{},"HEAT":{},"OFF":{"disabled":true}}},"networkInterface":{"linkQualityIndicator":{"access":"read","rssi":{"access":"read","type":"string"},"type":"string","values":{"EXCELLENT":{},"GOOD":{},"POOR":{},"UNDEFINED":{},"VERY_GOOD":{},"VERY_POOR":{}}},"swVersion":{"access":"read","type":"string"}},"sleepMode":{"access":"readwrite","type":"string","values":{"OFF":{},"ON":{}}},"startTime":{"access":"readwrite","max":86400,"min":0,"step":1800,"type":"number","values":{"0":{},"1800":{},"3600":{},"5400":{},"7200":{},"9000":{},"10800":{},"12600":{},"14400":{},"16200":{},"18000":{},"19800":{},"21600":{},"23400":{},"25200":{},"27000":{},"28800":{},"30600":{},"32400":{},"34200":{},"36000":{},"39600":{},"43200":{},"46800":{},"50400":{},"54000":{},"57600":{},"61200":{},"64800":{},"68400":{},"72000":{},"75600":{},"79200":{},"82800":{},"86400":{}}},"stopTime":{"access":"readwrite","max":86400,"min":0,"step":1800,"type":"number","values":{"0":{},"1800":{},"3600":{},"5400":{},"7200":{},"9000":{},"10800":{},"12600":{},"14400":{},"16200":{},"18000":{},"19800":{},"21600":{},"23400":{},"25200":{},"27000":{},"28800":{},"30600":{},"32400":{},"34200":{},"36000":{},"39600":{},"43200":{},"46800":{},"50400":{},"54000":{},"57600":{},"61200":{},"64800":{},"68400":{},"72000":{},"75600":{},"79200":{},"82800":{},"86400":{}}},"targetTemperatureC":{"access":"readwrite","default":16,"max":32,"min":16,"schedulable":true,"step":1,"type":"temperature"},"uiLockMode":{"access":"readwrite","type":"boolean","values":{"OFF":{},"ON":{}}},"verticalSwing":{"access":"readwrite","schedulable":true,"type":"string","values":{"OFF":{},"ON":{}}}}

https://www.electrolux.se/homecare/air-comfort/air-conditioners/portable-air-conditioner/exp35u539cw/
https://hub.docker.com/r/dannyyy/electrolux-mqtt
https://github.com/dannyyy/electrolux_mqtt

/Magnus Granath

---------------------------------------------------------------------------------------------------------------------------------------
To request a new device, install the Electrolux/AEG OCP Homey App

Add your email and password to the app Configure settings.

Then add a New Device, choose the Electrolux/AEG OCP app Brand, and choose the Unknown device and if you have any appliance, it should be found and added. 

I will need the Appliance State {json} and Appliance Capabilities {json} files that are published in the device Advanced Settings when you install the Unknown device. Include these two data files in your submission below.

Without this information, we cannot add support for your device, and the issue will be closed.

For example:

```
2024-06-28T03:07:51.553Z [log] [ElectroluxAEGApp] [{"applianceId":"XXXXXXXX_01:xxxxxxx-xxxxxx","applianceData":{"applianceName":"Dryer","created":"2024-06-25T06:35:21.260Z","modelName":"TD"},"properties":{"desired":{},"reported":{"doorState":"OPEN","timeToEnd":-1,"networkInterfaceAlwaysOn":"ON","miscellaneous":{},"applianceUiSwVersion":"URDB0A3H","applianceTotalWorkingTime":7200,"remoteControl":"NOT_SAFETY_RELEVANT_ENABLED","dryingNominalLoadWeight":65535,

        <<SNIP WE'VE SHORTENED THIS FOR THE EXMAPLE, PLUS PLEASE KEEP THE ENTIRE JSON IN YOUR COPY/PASTE>>

"tDEconomy_Eco":false,"tDEconomy_Quick":false,"refresh":false,"dryingTime":65535,"memoryId":20,"programUID":"MACHINE_SETTINGS_HIDDEN_TEST","antiCreaseValue":255,"tDEconomy_Night":false},"cycleMemory1":{"reversePlus":false,"tDEconomy_Eco":false,"tDEconomy_Quick":false,"refresh":false,"dryingTime":65535,"memoryId":30,"programUID":"MACHINE_SETTINGS_HIDDEN_TEST","antiCreaseValue":255,"tDEconomy_Night":false}},"metadata":{}},"status":"enabled","connectionState":"connected"}]
```

Finally, please link to more information about the device, e.g. the manufacturer's website to assist with images and icons that will be needed to complete the app update and publish in the app store.

**Comment by gslender** [comment]
Perfect!!

I should have an update out soon with support for Air Conditioning

**Comment by Granath67** [comment]
super...
thanks and have a nice weekend..

**Comment by gslender** [comment]
Try this test app

https://homey.app/a/com.electrolux-aeg.ocp/test/

**Comment by Granath67** [comment]
Hi!

Homey connects with the AC and get some information from it, but Homey Pro Can’t control the AC.

😊

 

 





 



 

Från: Grant Slender ***@***.***> 
Skickat: den 14 september 2024 03:58
Till: gslender/com.electrolux-aeg.ocp ***@***.***>
Kopia: Granath67 ***@***.***>; Author ***@***.***>
Ämne: Re: [gslender/com.electrolux-aeg.ocp] New Device: Comfort 600 Portabel AC BTU 12000 (Issue #9)

 

Try this test app

https://homey.app/a/com.electrolux-aeg.ocp/test/

**Comment by gslender** [comment]
I just updated the app again just now. It is now version 1.4.6. I added some more reported details that might be more useful. You may need to delete the device and recreate it.

Also, can you provide more details about what you can or can't control or what you believe you should be able to control?

Try to remember I don't have the appliance, so I cannot test anything - and so 100% rely on details from you to help me troubleshoot issues and debug problems. If you provide very little details, then there is not much I can do.

**Comment by Granath67** [comment]
Thats okey, I will do my best to report to you.!

For now, Homey can read the stat off the AC but can’t control it.

 

Function to a good start:

*	On (Works not)
*	Off (Works not)
*	Get measure temperature (working)
*	Set target temperature (Getting a rede popup messaging “Missing Capability Listner: target_temperature”)
*	Get Alerts 
*	Start Sleepmode 
*	Start fencing movement

 

Now I must walk the dog now. :)

 

/Magnus

 

Från: Grant Slender ***@***.***> 
Skickat: den 14 september 2024 08:39
Till: gslender/com.electrolux-aeg.ocp ***@***.***>
Kopia: Granath67 ***@***.***>; Author ***@***.***>
Ämne: Re: [gslender/com.electrolux-aeg.ocp] New Device: Comfort 600 Portabel AC BTU 12000 (Issue #9)

 

I just updated the app again just now. It is now version 1.4.6. I added some more reported details that might be more useful. You may need to delete the device and recreate it.

Also, can you provide more details about what you can or can't control or what you believe you should be able to control?

Try to remember I don't have the appliance, so I cannot test anything - and so 100% rely on details from you to help me troubleshoot issues and debug problems. If you provide very little details, then there is not much I can do.

**Comment by Granath67** [comment]
Hi Grant!

I have installed the 1.4.7. and tried some flows.

I’m not a developer but I will try to test and troubleshoot the app as good as I can.

Next week I’m away and will be back at home at Wednesday evening, but meanwhile I can test a little and see how the Electrolux App reacts but I can’t see or hear the AC..

Give direction what I should try and I will answer you as good I can..

 

/Magnus

 

Från: Grant Slender ***@***.***> 
Skickat: den 14 september 2024 08:39
Till: gslender/com.electrolux-aeg.ocp ***@***.***>
Kopia: Granath67 ***@***.***>; Author ***@***.***>
Ämne: Re: [gslender/com.electrolux-aeg.ocp] New Device: Comfort 600 Portabel AC BTU 12000 (Issue #9)

 

I just updated the app again just now. It is now version 1.4.6. I added some more reported details that might be more useful. You may need to delete the device and recreate it.

Also, can you provide more details about what you can or can't control or what you believe you should be able to control?

Try to remember I don't have the appliance, so I cannot test anything - and so 100% rely on details from you to help me troubleshoot issues and debug problems. If you provide very little details, then there is not much I can do.

**Comment by gslender** [comment]
Hi Magnus, Please don't reply to the emails you are receiving. It is really a bad way to update the issue as it copies in the past along with your response in the email. I'd prefer if you update the issue ticket in GitHub directly.

Please try v1.4.8 test release. You will need to delete the device and recreate it as the onoff buttons have been added

**Comment by gslender** [comment]
Okay, so turning the AC "off" is not working - is that correct? On via the button works but not off ?? That's wierd!?

All of the execute_command should not work at all - so not surprised that pause/stop/reset doesn't work. It shouldn't work. I will clean up this and for the next release, make sure you delete the device and re-add it so that it re-creates the capabiliities correctly.

I will fix the missing capability listner for thermostat_mode - my mistake in that I forgot about that.

We will get there eventually :-)

**Comment by gslender** [comment]
Can you send me a diagnostic of the AC not working, not turning on/off etc please - there are some logs that should be created that will help me understand why the off isn't working. Thanks

**Comment by gslender** [comment]
I've push out v1.4.10 which might sort the above issues. If not, please send me an app diagnostic report after you have attempted some actions

**Comment by Granath67** [comment]
Hi! 
When I “Turned on” the AC manual in Homey in the same second the “Electrolux AEG” “Turned off”, but the AC stills going on.

Functions I’ve tried in a flow:
“Toggle on or off” works only to turn on.
“Turn on” works
“Turn off" works
But the Homey still indicates that the “AC is turned off.”

**Comment by gslender** [comment]
As per my last comment, please send me an app diagnostics

**Comment by gslender** [comment]
Build 51 / v1.4.13 has some fixes that might resolve this....

https://homey.app/a/com.electrolux-aeg.ocp/test/

**Comment by Granath67** [comment]
Hi! 
Diagnostics Report: 0aa300d1-a2c4-4c94-b239-51b3a7c1bf39

I have uninstall the app and install it again and add the device.
Homey says 
"Device Unavailable
This device is currently unavailable."
But I can control it with the org. app from Electrolux.
